spawn:
  world: Lobby
  x: -780.5819478971214
  y: 7.0
  z: -502.473062698298
  yaw: 90.300095
  pitch: -0.3000066

# 活动范围设置 (x, z 坐标)，默认为0表示不限制
activity-range:
  # 点1坐标
  point1:
    x: 0
    z: 0
  # 点2坐标
  point2:
    x: 0
    z: 0

# 数据库配置
database:
  host: localhost
  port: 3306
  username: root
  password: password